Makefile
README.md

Because
- we want to explain how VDP works
This commit
- add how VDP works (part1)
- will add supported connectors in the following PR 
- add quick start section structure
- add build docker image in docs and Makefile

docs: add how VDP works and quick start structure

---

README.md

Because
- need to refactor the quick start script to be simpler
This commit
- update quick start script
- update the banner image name

docs: refactor quick start script to be simpler

---

Makefile
README.md
backends/pipeline-backend/config/config.yaml
examples-go/create-pipeline/main.go
examples-go/deploy-model/main.go
examples-go/test-model/main.go
examples-go/trigger-pipeline/main.go
go.mod
go.sum

Because
- Have better user experience of the section `Quick start`
- Examples should have explicitly input instead of hardcoded
This commit
- modify README.md
- add parameter while executing examples

docs: modify README.md and fix bug in examples

---

.github/workflows/add-issue-to-prj.yml
.github/workflows/add-pr-to-prj.yml

Because
- we'd like to track issues and PRs in the [VDP](https://github.com/orgs/instill-ai/projects/5) project.
This commit
- add Github Actions to add issues and PRs to the VDP project according to [automating the project (beta)](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/managing-the-visibility-of-your-projects)

ci: add issue and pr to VDP project

---

.env
Makefile
README.md
docker-compose.yml

Because
- need to tell uses that the `make all` process may take time for a specific reason
This commit
- add warning message in `make all`
- change the description of README.md
- close #81

chore(doc): add warning message in `make all` and README.md

---

.github/workflows/add-issue-to-prj.yml
README.md

Because
- we are continuously improving the documentation
This commit
- update README.md

docs: update README.md

---

.gitignore
docker-compose.yml
examples-go/create-pipeline/main.go
examples-go/deploy-model/main.go
examples-go/test-model/main.go
examples-go/trigger-pipeline/main.go
go.mod
go.sum
pkg/temporal/activities.go
tests/integration-tests/model-backend-rest.js
tests/integration-tests/pipeline-backend-constants.js
tests/integration-tests/pipeline-backend-rest.js

Because
- the latest `protobufs` has achieved better consistency and adopted the best practice of protocol buffer, this repo is required to update the new protocol
This commit
- make the adoption of the latest `protobufs`

refactor: adopt latest protobufs

---

README.md

Because
- we want to share the career opportunities with the community
This commit
- add we're hiring section

docs: add we're hiring info

---

README.md
examples/streamlit/stomata/README.md
examples/streamlit/stomata/requirements.txt
examples/streamlit/stomata/streamlit_main.py
examples/streamlit/stomata/utils.py
examples/streamlit/yolov7/main.py

Because
- we want to add more use cases
This commit
- add stomata instance segmentation example

docs: add stomata instance segmentation example

---

.env
Makefile
docker-compose-dev.yml
docker-compose.yml

Because
- the model-backend support deploy/undeploy model instance asynchronously
This commit
- add elasticsearch container for Temporal when using SearchAttribute

chore(model): update model backend async

---

docker-compose.yml
protocol/vdp_protocol.yaml

Because
- `model-backend-worker-init` was moved inside `model-backend-worker`
This commit
- update `model_backend_worker` entrypoint

fix: fix docker-compose

---

.github/workflows/integration-test-latest.yml

Because
- fix unchanged test branch ref
This commit
- update integration-test ref branch

ci(actions): fix ref branch

---

examples/instill/streamlit-instance-segmentation-sync-http-http-stomata/README.md
examples/instill/streamlit-instance-segmentation-sync-http-http-stomata/main.py
examples/streamlit-instance-segmentation-sync-http-http/README.md
examples/streamlit-instance-segmentation-sync-http-http/main.py
examples/streamlit-object-detection-sync-http-http/main.py
examples/vdp-101/async/README.md
examples/vdp-101/async/trigger.py
examples/vdp-101/sync/README.md
examples/vdp-101/sync/sync-http-base64.py
examples/vdp-101/sync/sync-http-multipart.py
examples/vdp-101/sync/sync-http-url.py
examples/vdp-101/sync/utils.py

Because
- we need to update the examples for adopting the new protobuf
This commit
- update examples

chore(examples): update vdp tutorial and code examples

---

charts/vdp/templates/controller/configmap.yaml

Because
- fix misplaced configs
This commit
- remove unused configs

chore(helm): remove controller unused configs

---

Makefile
charts/vdp/templates/console/deployment.yaml
charts/vdp/values.yaml

Because
- We need automated local helm integration test.
This commit
- Provide local helm integration test with model tests for release and latest.

chore(helm): add local helm integration tests

---

model-hub/model_hub_cpu.json
model-hub/model_hub_gpu.json

Because
- the ids of some models are inaccurate
This commit
- update model ids

chore(model-hub): update model hub model ids

---

charts/vdp/templates/_helpers.tpl
charts/vdp/templates/connector/configmap.yaml
charts/vdp/templates/connector/deployment.yaml
charts/vdp/templates/model/deployment.yaml
charts/vdp/templates/temporal/admintools-deployment.yaml
charts/vdp/values.yaml
docker-compose.latest.yml
docker-compose.yml

Because
- remove temporal dependency from connector-backend
This commit
- remove temporal dependency from connector-backend

chore(connector): remove connector temporal dependency

---

charts/vdp/templates/_helpers.tpl
charts/vdp/templates/pipeline/configmap.yaml
charts/vdp/templates/pipeline/deployment.yaml
charts/vdp/templates/temporal/admintools-deployment.yaml
charts/vdp/values.yaml
docker-compose.latest.yml
docker-compose.yml

Because
- we have a new pipeline-backend-worker need to be included in deployment
This commit
- add pipeline-backend-worker service

chore(docker-compose,helm): add pipeline-backend-worker service

---

charts/vdp/values.yaml

Because
- the connector dbVersion has updated 
This commit
- update connector dbVersion in `values.yaml`

chore(helm): update connector dbVersion

---

charts/vdp/templates/connector/configmap.yaml
charts/vdp/templates/mgmt/configmap.yaml
charts/vdp/templates/model/configmap.yaml
charts/vdp/templates/pipeline/configmap.yaml
charts/vdp/values.yaml

Because
- usage collection configuration in each component has been changed
This commit
- update the Helm chart usage collection configuration

chore(helm): update usage config

---

charts/vdp/templates/_helpers.tpl
charts/vdp/templates/pipeline-backend/configmap.yaml

Because
- adopt pipeline influx config
This commit
- adopt pipeline influx config

chore(helm): adopt pipeline influx config

---

.github/workflows/helm-integration-test-backend.yml
.github/workflows/helm-integration-test-latest.yml
.github/workflows/helm-integration-test-release.yml

Because
- We have to automate helm-integration-test-latest and helm-integration-test-release
This commit
- add helm-integration-test-latest|release workflow

ci(workflow): add helm-integration-test-latest|release workflow

---

.github/workflows/helm-integration-test-backend.yml

Because
- the helm ci test failed due to not port forwarding
This commit
- fix port forwarding

chore(ci): fix port forward

---

.github/workflows/make-all.yml
.github/workflows/make-latest.yml

Because
- We have to automate test healthcheck endpoint of latest (make latest PROFILE=all) and release (make all)
This commit
- create workflow to automate test make latest

ci(workflow): create workflow to automate test make latest

---

charts/vdp/values.yaml

Because
- the pipeline db version has been updated
This commit
- update pipeline db version

chore(helm): update pipeline db version

---

examples/vdp-101/async/process.py

chore(examples): fix typo in process.py

---

.env
.github/CONTRIBUTING.md
.github/workflows/helm-integration-test-backend.yml
.github/workflows/integration-test-backend.yml
.github/workflows/make-all.yml
.github/workflows/make-latest.yml
Dockerfile
Makefile
README.md
charts/vdp/templates/_helpers.tpl
charts/vdp/templates/connector-backend/configmap.yaml
charts/vdp/templates/connector-backend/deployment.yaml
charts/vdp/templates/controller-vdp/configmap.yaml
charts/vdp/templates/controller-vdp/deployment.yaml
charts/vdp/templates/internal/auto-tls.yaml
charts/vdp/templates/pipeline-backend/configmap.yaml
charts/vdp/templates/pipeline-backend/deployment.yaml
charts/vdp/values.yaml

Because
- Instill Base is going to be promoted to Instill Core
This commit
- refactor and rename all `base` to `core`

refactor(all): rename base to core

---

charts/vdp/values.yaml

Because
- the pipeline db version has been updated
This commit
- update db version

chore(helm): update db version

---

charts/vdp/values.yaml

Because
- we need to update the resources for pipeline backend containers.
This commit
- update the resources for pipeline backend containers

chore(helm): update resources for pipeline backend containers

---

.env
Makefile
docker-compose-build.yml

Because
- We need to add the console integration tests back.
This commit
- Adds console integration test in Makefile.

ci(makefile): add console integration test in Makefile

---

model-hub/model_hub_test.json

Because
- We want to define a list of test models for integration-test
This commit
- add a model list for integration-test

chore(model_hub): add test model list for integration-test

---

charts/core/values.yaml

Because
- The pipeline db version needs to be updated.
This commit
- Upgrades pipeline db version to 15.

chore(helm): upgrade pipeline db version to 15

---

charts/core/values.yaml
model-hub/model_hub_gpu.json
model-hub/model_hub_test.json

Because
- Predeploy model lists has models which will be deployed under different namespace
This commit
- add namespace id and type in model-hub

chore(model-hub): update model-hub configs

---

charts/core/values.yaml

Because
- Model db version was outdated.
This commit
- Updates model db version.

chore(helm): update model db version

---

charts/core/values.yaml

Because
- The pipeline db version need to be updated.
This commit
- Updates pipeline db version to 21

chore(helm): update pipeline db version to 21

---

charts/core/values.yaml

Because
- The pipeline db version need to be updated.
This commit
- Updates pipeline db version to 24.

chore(helm): update pipeline db version to 24

---

charts/core/values.yaml

Because
- The model db version need to be updated.
This commit
- Updates model db version to 9.

chore(helm): update model db version to 9

---

.github/workflows/helm-integration-test-backend.yml
.github/workflows/helm-integration-test-console.yml
Makefile

Because
- The Makefile integration-test is not working.
This commit
- Fixes Makefile integration-test.

chore(makefile): fix Makefile integration-test

---

model-hub/model_hub_test.json

Because
- Add new test model to the list
This commit
- add multimodal test embedding model

chore(model-hub): add multimodal test embedding model

---

charts/core/values.yaml

This commit
- bump pipeline db version to 29

chore(helm): bump pipeline db version

---

charts/core/templates/pipeline-backend/deployment.yaml

This commit
- Increases pod timeoutSeconds for livenessProbe

chore(helm): increase pod timeoutSeconds for livenessProbe

---

README.md

Because
- artifact was released and a lot of content has changed
This commit
- updates the repo README

chore(readme): update README content

---

Dockerfile
charts/core/values.yaml

This commit
- update pipeline-backend db version

chore(helm): update pipeline-backend db version

---

charts/core/templates/pipeline-backend/configmap.yaml

chore(vdp): update config

---

README.md

Because
- README.md content is out-dated 
This commit
- update it

chore(README): update Instill Core stack

---

.env

Because
- A new console version has been released.
This commit
- Updates the console release tag.

chore(release): update console version

---

charts/core/templates/_helpers.tpl
charts/core/templates/artifact-backend/configmap.yaml
charts/core/templates/mgmt-backend/configmap.yaml
charts/core/templates/model-backend/configmap.yaml
charts/core/templates/openfga/deployment.yaml
charts/core/templates/pipeline-backend/configmap.yaml
charts/core/values.yaml

Because
- We have to fetch the secret from secret for database
This commit
- fetch secret from secret for database

chore(instill-core): fetch secret from secret for database

---

charts/core/templates/_helpers.tpl
charts/core/templates/artifact-backend/configmap.yaml
charts/core/templates/mgmt-backend/configmap.yaml
charts/core/templates/model-backend/configmap.yaml
charts/core/templates/pipeline-backend/configmap.yaml
charts/core/values.yaml

Because
- We have to fetch the secret from secret for influxdb cloud
This commit
- fetch the secret from secret for influxdb cloud

chore(instill-core): fetch the secret from secret for influxdb cloud

---

charts/core/templates/pipeline-backend/deployment.yaml
charts/core/templates/pipeline-backend/hpa.yml
charts/core/values.yaml

Because
- We have to create HPA for pipeline-backend-worker
- We have to fix the HPA of pipeline-backend
This commit
- create hpa for pipeline-backend-worker

chore(pipeline-backend): create hpa for pipeline-backend-worker

---

charts/core/templates/artifact-backend/configmap.yaml
charts/core/templates/mgmt-backend/configmap.yaml
charts/core/templates/model-backend/configmap.yaml
charts/core/templates/openfga/deployment.yaml
charts/core/templates/pipeline-backend/configmap.yaml

Because
- We have to fetch the secret from secret for the database's external replica
This commit
- (fetch the secret from secret for database external replica

chore(database): fetch the secret from secret for database external replica

---

Makefile
charts/core/templates/_helpers.tpl
charts/core/templates/api-gateway/deployment.yaml
charts/core/templates/artifact-backend/deployment.yaml
charts/core/templates/console/deployment.yaml
charts/core/templates/mgmt-backend/deployment.yaml
charts/core/templates/model-backend/deployment.yaml
charts/core/templates/openfga/deployment.yaml
charts/core/templates/pipeline-backend/deployment.yaml
charts/core/templates/temporal/server-deployment.yaml
charts/core/values.yaml

Because
- The reordering of the `docker compose` command improves readability and maintainability of the Makefile.
- The added annotations and container configurations in `values.yaml` enable more flexible and customizable deployments across different environments.
- These changes enhance the overall CI/CD workflow and make infrastructure configurations more consistent across development, testing, and production environments.
- The improvements support better Kubernetes integration and provide additional customization options for production deployments.
This commit
- Reorders `docker compose` command parameters in Makefile for improved readability
- Adds deployment annotations for API Gateway, Management Backend, and Pipeline Backend services
- Configures extra container support (init …

ci(helm,makefile): improve configuration

---

charts/core/templates/openfga/deployment.yaml
docker-compose.yml

This commit
- enables check-query cache for OpenFGA

chore(openfga): enable check-query cache

---

.github/workflows/releases.yml
charts/core/templates/kuberay/configmap.yaml
charts/core/templates/kuberay/post-install-job.yaml
charts/core/values.yaml

Because
- for local Helm deployment (mostly for testing), we'd like to see Ray-related pods to be in BestEffort mode
This commit
- fix wrong release tag
- revise the manifests

chore(helm,ray): update ray configuration

---

charts/core/templates/mgmt-backend/deployment.yaml
charts/core/templates/pipeline-backend/deployment.yaml

This commit
- adds Temporal TLS mount for mgmt/pipeline-backend-init

chore(helm): add Temporal TLS mount for mgmt/pipeline-backend-init

---

Makefile.helper
charts/core/Chart.lock
charts/core/Chart.yaml
charts/core/README.md
charts/core/templates/NOTES.txt
charts/core/templates/_helpers.tpl
charts/core/values.yaml

Because
- we are replacing the observability stack with Grafana Stack.
This commit
- removes Jaeger

chore(helm): remove Jaeger

---

Makefile.helm
charts/core/Chart.lock
charts/core/Chart.yaml
charts/core/templates/api-gateway/configmap.yaml
charts/core/templates/artifact-backend/configmap.yaml
charts/core/templates/grafana/configmap.yaml
charts/core/templates/grafana/secret.yaml
charts/core/templates/mgmt-backend/configmap.yaml
charts/core/templates/model-backend/configmap.yaml
charts/core/templates/pipeline-backend/configmap.yaml
charts/core/values.yaml

This commit
- unifies dependency enabler flag.

chore(helm): unify dependency enabler flag
