instill-ai/instill-core

examples-go/test-model/main.go
Because
- When make a prediction request, the user needs to specify CV Task such as classification, object detection. Sample model yolov4 is detection Task
This commit
- type=1 for detection Task (note: type=0 for classification task)
=> fix: wrong type in sample model prediction

Makefile, docker-compose.yml
Because
- we'd like to provide good local dev experience using docker-compose and Makefile
This commit
- fix `make help`, so the user can learn the make commands by:
```
$ make help
Make Application using Docker-Compose files.
Usage:
make <target> (default: help)
Targets:
all           Build and launch all services
logs          Tail all logs with -n 10.
stop          Stop all components.
start         Start all stopped components.
restart       Restart all components.
rm            Remove all stopped components containers.
down          Down all components.
images        List all images of components.
ps            List all component containers.
prune         Remove all containers and delete volume
build         Build local docker image
help          Show this help.
```
- make `make all` …
=> chore: improve docker compose and Makefile

examples-go/deploy-model/main.go, examples-go/test-model/main.go, go.mod, go.sum
Because
- Model protobuf have updated with CV Task and Version in CreateModel method
This commit
- Add CV Task and Version when CreateModel method
- Increase timeout for uploading/predicting model in examples-go
=> chore: update model protobuf

.github/semantic.yml
Because
- we've adopted conventional commits for both PR and commit title.
This commit
- add [Semantic PR](https://github.com/apps/semantic-pull-requests) configuration file
=> ci: add semantic PR config

docker-compose.yml, go.sum
Because
- we have an existing PostgreSQL running, then we can remove Cassandra as Temporal's storage for resource-saving point of view
This commit
- remove Cassandra
- change configuration in temporal
- correct go.sum
=> chore(temporal): use postgres as temporal's storage

docker-compose.yml
Because
- Temporal now need the dependency of PostgreSQL not Cassandra
This commit
- change correct dependency for temporal
=> fix(docker-compose): change correct dependency for temporal

Makefile, docker-compose.yml
Because
- we need to have a document page for REST endpoints
This commit
- add redoc that supports multiple openapi spec.
=> docs: add redoc that supports multiple openapi spec

README.md, docker-compose.yml, examples-go/deploy-model/main.go, go.mod, go.sum
Because
- To make the model API convenient to users, the model version should be auto increased
This commit
- Update model backend which auto increase model version when user create a model with an existed name
- Update example corresponding with the latest model protobuf
- Fix a small typo in README
=> fix(model): update model backend without specify version when creating model

README.md
Because
- guideline for users to prepare their own model will be helpful and need to describe in README.md
This commit
- add preparing model section
- describe support framework, CV Task
- close #53 
- close #54 
- close #55
=> docs: add guideline to create a pipeline using user's  own model

Makefile, docker-compose.yml
Because
- we'd like the official conda-pack to be loaded by the Triton server without the user intervening. 
This commit
- use the triton-conda-env CPU container to leverage the shared volume to load conda-pack into the Triton container
- update Makefile accordingly
=> ci: use container for conda-pack

Makefile
Because
- the Makefile was broken in the last commit
- we would like to gain observability of service processes
This commit
- fix Makefile
- introduce `make top`
=> ci: fix Makefile and add make top

Makefile, README.md
Because
- API reference section is empty
This commit
- add API reference
- add `make doc` for launching Redoc at https://localhost:3000
- add warning for `main` branch: codebase is under-development
- remove conda-pack downloading from quick start
- add warning for long docker image pulling time
- change the section order
- add clean up section in quick start
=> docs: add api reference section and remove conda-pack downloading

.github/workflows/add-pr-to-prj.yml, README.md, docker-compose.yml
Because
- we need to fix the version for model-backend and pipeline-backend in docker-compose
This commit
- pin down the initial versions
=> ci: fix service image versions in docker-compose

examples-go/deploy-model/main.go, examples-go/test-model/main.go
Because
- There are some typos in examples-go
This commit
- Fix those typos
- close #75
=> fix: typos in examples-go

examples-go/test-model/main.go
Because
- There are some typos in examples-go
This commit
- Fix those typos (use[ vscode plugin ](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)for typo detection)
- close #75
=> fix: some typos in examples-go

.github/workflows/add-issue-to-prj.yml, .github/workflows/add-pr-to-prj.yml, .github/workflows/coverage.yml
Because
- we would like to regularly check test coverage of the codebase
This commit
- set up codecov action
- make GitHub Actions workflow name consistent
=> ci: add codecov action

Makefile, docker-compose.yml
Because
- we want to manage user account
This commit
- add `mgmt-backend` for user management
- refactor backend ports
- mgmt-backend: 8080
- pipeline-backend: 8081
- model-backend: 8083
=> chore(mgmt-backend): add mgmt backend

docker-compose-dev.yml, docker-compose.yml
Because
- Instead of one for each backend, OpenAPI is [a single merged file](https://github.com/instill-ai/protobufs/blob/main/openapiv2/openapiv2.swagger.yaml)
This commit
- use Redocly official image
- render the single OpenAPI Swagger YAML
=> fix: fix OpenAPI swagger service

protocol/vdp_protocol.yaml
Because
- we want to standardise Computer Vision (CV) tasks using JSON schema
This commit
- add the VDP protocol file that includes JSON schema for model batch outputs of all supported CV tasks
=> chore: add vdp protocol file

.env
Because
- DVC pulls multiple files from cloud storage needs List permission
This commit
- Update DVC to pull one by one model weight file
=> chore(model): update model-backend

protocol/vdp_protocol.yaml
Because
- support instance segmentation task in VDP
This commit
- add protocol of instance segmentation task
=> chore: add protocol of instance segmentation task

protocol/vdp_protocol.yaml
Because
- the length of RLEs are different between objects, so it could not broadcast in the Triton server output
This commit
- update RLE output format to string (example: [1, 3, 4] => "1,3,4")
- to decode RLE need to convert the string to an array
=> chore(model): update RLE output format to string

.env, Makefile, docker-compose-dev.yml
Because
- The console integration test is ready
This commit
- add console e2e test into vdp
- update ITMODE=true when running integration-test. When the flag ITMODE is enabled, the integration-test use dummy models instead of pulling from GitHub, HuggingFace, or ArtiVC to reduce the impact of the internet connection.
co-author: @Phelan164
=> feat: add console e2e test into vdp

.github/workflows/integration-test.yml, Makefile
Because
- playwright dependencies are missing in GitHub Action Runner env, and
- we would like to run the integration test on all PR branches.
This commit
- use `npx playwright install --with-deps`
- change integration-test GitHub action script to trigger all branches
=> ci: fix integration-test

.env, examples/async/yolov7/main.py, examples/streamlit/stomata/README.md, examples/streamlit/stomata/streamlit_main.py, examples/streamlit/yolov7/main.py
Because
- we want to use the latest services
This commit
- bump pipeline-backend from `0.8.0-alpha` to `0.9.2-alpha`
- bump connector-backend from `0.6.0-alpha` to `0.7.1-alpha`
- bump model-backend from `0.8.1-alpha` to `0.9.1-alpha`
- bump mgmt-backend from `0.2.6-alpha` to `0.2.7-alpha`
- bump console from `0.12.0-alpha` to `0.13.0-alpha`
- update the examples
=> chore: bump up backends and frontend

protocol/vdp_protocol.yaml
Because
- support semantic segmentation in the VDP task
This commit
- add semantic segmentation in `protocol/vdp_protocol.yaml`
- change `label` to `category` in instance segmentation for naming consistency
- close #163 
- close #164
=> chore(model): update model output protocol

.github/workflows/add-issue-to-prj.yml, .github/workflows/add-pr-to-prj.yml, README.md, examples/streamlit/stomata/README.md, examples/streamlit/stomata/streamlit_main.py, examples/streamlit/yolov7/main.py
Because
- instead of Visual Data Preparation, VDP is _Versatile Data Pipeline_ now. We realise that as a general ETL infrastructure, VDP is capable of processing all kinds of unstructured data, and we should not limit its usage to only visual data. That's why we replace the word Visual with Versatile. Besides, the term Data Preparation is a bit misleading, users often think it has something to do with data labelling or cleaning. The term Data Pipeline is definitely more precise to capture the core concept of VDP.
This commit
- update to Versatile Data Pipeline
=> chore: update to Versatile Data Pipeline

Makefile
Because
- There has a typo in makefile
This commit
- Fix the typo
=> fix: fix typo in makefile

README.md
Because
- triton image build with nvidia runtime fail with missing items in prerequisite
This commit
- add required dependencies in prerequisite section to enable gpu support
=> docs: add nvidia-docker to prerequisites section for gpu support

.github/workflows/images-example.yml, examples/streamlit/instance_segmentation/README.md, examples/streamlit/instance_segmentation/main.py, examples/streamlit/stomata/Dockerfile, examples/streamlit/stomata/README.md, examples/streamlit/stomata/main.py, examples/streamlit/yolov7/README.md, examples/streamlit/yolov7/main.py
Because
- we want to deploy the demo online
This commit
- add Dockerfile for stomata example
- push the example docker image to DockerHub
- update the pipeline backend base URL to use the API gateway entry point for all examples
=> chore: add Dockerfile for stomata example

.github/workflows/integration-test-console.yml
Because
- The frontend build will take too many space, we need to clean up some unneeded lib to make it stable
This commit
- clean up disk space before action
=> feat: clean up disk space

Makefile
Because
- cpu version of triton-conda-env image works on apple silicon machines, there is no need for standalone m1 image
This commit
- remove logic clause for apple silicon machines in Makefile
=> chore: remove standalone m1 conda image dependency

.github/workflows/integration-test-console.yml
Because
- console e2e config is wrong when set up the workflow
This commit
- fix console e2e config
=> fix: fix console e2e config

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
Because
- we want to provide a series of issue templates to standardise vdp issues
This commit
- add issue templates
=> ci: add issue templates

charts/vdp/templates/connector/configmap.yaml, charts/vdp/templates/model/configmap.yaml, charts/vdp/templates/pipeline/configmap.yaml
Because
- the latest Helm release v0.1.2-alpha is buggy
This commit
- fixes the configmaps
=> chore(helm): fix configmaps

docker-compose.yml
Because
- downloading the models take a long time, so it's useful to cache these downloaded model
This commit
- add volume for the model-backend caching
=> chore(docker-compose): add cache volume for model backend

model-hub/model_hub_cpu.json
Because
- provide a list of models that can be deployed via VDP on device without GPU and the model instance concept has been removed
This commit
- update the model configuration in the model hub list
=> chore(model-hub): update model hub for device without GPU

charts/vdp/templates/model/deployment.yaml, docker-compose.yml
Because
- remove model instance concept in the model-backend
This commit
- remove model instance search attribute in Temporal
=> chore(temporal): remove model instance search attribute in Temporal

charts/vdp/templates/temporal/admintools-deployment.yaml, docker-compose.yml
Because
- the Temporal cloud does not support search attributes
This commit
- remove search attributes creation in Temporal admin tool
=> chore(temporal): remove search attributes

docker-compose.latest.yml
Because
- `model_backend_init_model` should run for all profiles except `model` itself.
This commit
- Add more profile for `model_backend_init_model`
=> chore(docker-compose): fix model_backend_init_model not running for some profiles

charts/vdp/templates/apigateway/configmap.yaml, charts/vdp/templates/apigateway/deployment.yaml, charts/vdp/templates/connector/configmap.yaml, charts/vdp/templates/connector/deployment.yaml, charts/vdp/templates/console/deployment.yaml, charts/vdp/templates/controller/configmap.yaml, charts/vdp/templates/controller/deployment.yaml, charts/vdp/templates/mgmt/configmap.yaml, charts/vdp/templates/mgmt/deployment.yaml, charts/vdp/templates/model/configmap.yaml, charts/vdp/templates/model/deployment.yaml, charts/vdp/templates/model/post-install-job.yaml, charts/vdp/templates/pipeline/configmap.yaml, charts/vdp/templates/pipeline/deployment.yaml, charts/vdp/templates/temporal/server-deployment.yaml, charts/vdp/values.yaml
Because
- Temporal Cloud requires TLS auth and specific namespace
This commit
- accommodate Helm chart to the required setup
=> chore(helm): add logics to accommodate Temporal Cloud

.github/workflows/integration-test-backend.yml, Makefile
Because
- need to simplify the setting for integration test mode
This commit
- refactor integration test mode by using `API_GATEWAY_HOST` and `API_GATEWAY_PORT`
=> chore(actions,makefile): refactor integration test mode

Makefile, charts/vdp/templates/triton/deployment.yaml, charts/vdp/values.yaml
Because
- The integration test host for linux system in Makefile is wrong
- Currently, the posgreSQL set max_connection: 100. But here we set each backend's connection pool size to `1024`. `1024` connection * 4 backend is far exceed `100`. We should make it smaller.
- The `triton.nvidiaVisibleDevices = all` config will stop the triton server running on cpu-only machine
- The console e2e test won't work on linux machine
This commit
- Fix integration test host for linux system in Makefile 
- Update connection pool size
- Pass `nvidiaVisibleDevices` from env.
- Fix console e2e test by removing `serverApiGatewayBaseUrl` from makefile helm install
=> chore(makefile): fix linux integration test host

examples/instill/streamlit-instance-segmentation-sync-http-http-stomata/main.py, examples/metabase-object-detection-async-http-postgres/main.py, examples/streamlit-instance-segmentation-sync-http-http/main.py, examples/streamlit-object-detection-sync-http-http/main.py, examples/vdp-101/async/trigger.py, examples/vdp-101/sync/sync-http-base64.py, examples/vdp-101/sync/sync-http-multipart.py, examples/vdp-101/sync/sync-http-url.py
Because
- we've updated the trigger endpoints
This commit
- update SYNC pipeline endpoint to `/triggerSync` and `/triggerSyncMultipart`
- update SYNC pipeline endpoint to `/triggerAsync` and `/triggerAsyncMultipart`
=> chore(examples): update trigger endpoints

charts/vdp/templates/connector/deployment.yaml, docker-compose.yml
Because
- we need to download the Airbyte images when `connector-backend-init`, but we can not use `dind` in pod initContainers. So we need to use host docker to download the images.
This commit
- use host docker to pull images when connector-backend-init
=> chore(helm,docker-compose): use host docker to pull images when connector-backend-init

charts/vdp/templates/_helpers.tpl, charts/vdp/templates/api-gateway-vdp/configmap.yaml, docker-compose.yml
Because
- remove setting PROJECT from hostname and rely on env variable instead in `api-gateway`
This commit
- add api-gateway project env
=> chore(helm,compose): add api-gateway project env

.github/workflows/integration-test-backend.yml, Makefile
Because
- Some of our test-cases may be cross projects, we need to use different apigateway endpoints
This commit
- update integration test params
=> chore(makefile): update integration test params

charts/vdp/values.yaml
Because
- the db version for pipeline-backend has been upgraded
This commit
- upgrade pipeline-backend db version in helm charts
=> chore(helm): upgrade pipeline-backend db version

Makefile
Because
- remove tmp folder will fail due to permission issue in `ubuntu`
This commit
- update rm command
=> chore(makefile): fix `mktemp` folder permission issue in ubuntu

docker-compose.yml
Because
- the latest docker compose requires explicit flag `external: true` for using existing network
- the latest docker compose no longer allows launching with depended services filtered out. From the microservice design principle, the services should not have hard dependency on each other anyway.
This commit
- add the network flag
- remove cross-service dependency
=> ci(docker-compose): fix PROFILE setup and network

charts/vdp/templates/connector-backend/configmap.yaml, charts/vdp/values.yaml
Because
- we have a config to enable loading pre-built connectors
This commit
- add `prebuiltconnector.enabled` config in helm charts
=> chore(helm): add prebuiltconnector.enabled config

charts/vdp/templates/connector-backend/deployment.yaml
Because
- we need to pass some env variable into connector_backend_init
This commit
- add extra env to connector_backend_init
=> chore(helm): add extra env to connector_backend_init

charts/vdp/templates/_helpers.tpl, charts/vdp/templates/api-gateway-vdp/deployment.yaml, charts/vdp/templates/pipeline-backend/configmap.yaml, charts/vdp/values.yaml
Because
- add influxdb cloud section to pass different values than self-hosted influxdb
- separate out observability and prometheus-stack
This commit
- add influx cloud config section in values.yaml
- add prometheusStack tag
=> chore(vdp): add influx cloud config

charts/vdp/templates/connector-backend/deployment.yaml
Because
- we wanted to share airbyte image from connector-backend-init to connector-backend container
This commit
- mount docker image cache volume to connector-backend-init and connector-backend container
=> chore(helm): mount docker image cache volume

Makefile
Because
- `make all` and `make latest` require `vdp-compose:{release,latest}` image to build local release/latest images and to spin up a Instill Base cluster via DinD
This commit
- add `make build-release` and `make build-latest` in all and latest target respectively
=> ci(makefile): fix local build vdp-compose image

charts/vdp/templates/connector-backend/deployment.yaml
Because
- The Airbyte images will download twice in `connector-backend-init` and `connector-backend`
This commit
- Optimize Airbyte images pulling problem. The images will be downloaded only once in `connector-backend-init`
=> chore(helm): optimize Airbyte images pulling problem

charts/vdp/templates/connector-backend/configmap.yaml
Because
- support metric export to influxdb in connector-backend
This commit
- add influxdb config in helm connector configmap
=> chore(helm): add influxdb config in connector configmap

charts/vdp/templates/connector-backend/deployment.yaml, charts/vdp/values.yaml
Because
- the k8s copy-docker initContainer should be optional 
This commit
- make copy-docker step optional
=> chore(helm): make connector k8s copy-docker step optional

.env, Makefile
Because
- the original `EXTRA_PARAMS` is hard-coded for linux.
This commit
- rename `EXTRA_PARAMS` to `DOCKER_HELM_IT_EXTRA_PARAMS`
- put `DOCKER_HELM_IT_EXTRA_PARAMS` in `.env` to have a better extensibility
=> chore(makefile,env): rename `EXTRA_PARAMS` to `DOCKER_HELM_IT_EXTRA_PARAMS`

.github/workflows/integration-test-latest.yml, .github/workflows/integration-test-release.yml
Because
- we have to trigger integration test latest and release when push in main branch.
This commit
- update integration test release and latest workflow
=> ci(workflow): update integration test release and latest workflow

.env, Makefile
Because
- support persistent user uuid for docker compose launch
This commit
- add `user_uuid` file in config folder
- pass through `user_uuid` as env variable for `base` `mgmt-backend-init` pod
=> chore(env,makefile): add system config for persisten user_id

charts/vdp/values.yaml
Because
- the pipeline-backend db version has been upgraded
This commit
- upgrade pipeline db version
=> chore(helm): update pipeline db version

Makefile
Because
- the `uuidgen` tool is not installed in every environment
This commit
- use docker to generate `DEFAULT_USER_UID`
=> chore(makefile): use docker to generate DEFAULT_USER_UID

LICENSE, README.md
Because
- the README.md and LICENSE files are out-of-date
This commit
- update content
=> docs(LICENSE,README): make content up-to-date

.env, .github/workflows/make-all.yml, .github/workflows/make-latest.yml, Dockerfile, Makefile, docker-compose.yml
Because
- `make down` won't go smoothly from a `make all` instance due to missing `release` compose images
-  the current 3rd-party `uuidgen` image doesn't support arm64
This commit
- replace the Ubuntu image with Apline to save ~300MB for the compose image
- add related `release` compose images in `make down`
- add `make down` step in `make-all/latest` GA workflow to validate the complete flow
- move `uuidgen` into compose image so we don't need to use an external image
- make `~/.config/instill` folder logic and env variable `SYSTEM_CONFIG_PATH` in only the base project
=> ci(Makefile): optimise spin-up/tear-down flow

.github/workflows/helm-integration-test-release.yml, .github/workflows/integration-test-release.yml, .github/workflows/make-all.yml
Because
- we only need to run release related workflow in branch `release-please--branches--main` and tags event
This commit
- update GA workflow triggering event
=> ci(workflow): update GA workflow triggering event

Makefile
Because
- the `helm-integration-test-latest` script has bug
This commit
- fix `helm-integration-test-latest` bug
=> fix(makefile): fix `helm-integration-test-latest` bug

.github/workflows/helm-integration-test-backend.yml, .github/workflows/integration-test-backend.yml, Makefile
Because
- We have to automate make integration-test-latest|release and helm-integration-test-latest|release for mac
This commit
- add integration-test-latest|release workflow for mac
=> ci(workflow): add integration-test-latest|release workflow for mac

Makefile, docker-compose.yml
Because
- `make stop/start` was broken due to the containers used in docker compose `depends_on` that are removed after spin-up
This commit
- remove `docker compose rm -f` in `make all/latest`
- remove `make rm` and `make restart` (no use case)
- revert EDITION setting logic
=> ci(Makefile): fix make stop and start

charts/vdp/templates/pipeline-backend/deployment.yaml, charts/vdp/values.yaml
Because
- we need annotations for pipeline-backend for secret updation. 
This commit
- add annotations for pipeline-backend deployment.
=> chore(helm): add annotations for pipeline-backend deployment

README.md
Because
- we should use `make all` in "released" version
This commit
- update quick start section
=> docs(readme): update quick start section

charts/vdp/templates/connector-backend/hpa.yml, charts/vdp/templates/controller-vdp/hpa.yml, charts/vdp/templates/pipeline-backend/hpa.yml, charts/vdp/values.yaml
Because
- We have to create pod autoscaling to reduce downtime and disaster
This commit
- create horizontal pod autoscaling
=> chore(vdp): create horizontal pod autoscaling

README.md, release-please/config.json
Because
- we need to update version in README automatically in case human error
This commit
- use release-please to update version in README automatically
=> ci(release): update version in README automatically

model-hub/model_hub_gpu.json
Because
- adopt to updated gpu infra
This commit
- adopt to updated gpu infra
=> chore(model): update predeploy model tags

.github/workflows/helm-integration-test-backend.yml, .github/workflows/integration-test-backend.yml
Because
- We have to update logic to run integration test latest workflow on macos runner
This commit
- update logic for integration test latest run on macos runner
=> ci(workflow): update logic for integration test latest run on macos runner

examples/README.md
Because
- the documentation adopts the US spelling
This commit
- review the UK spelling to the US one, i.e., `visualisation` -> `visualization`
=> docs(example): update README.md

.env, .github/workflows/make-all.yml, .github/workflows/make-latest.yml, Makefile
Because
- the `core` repo is treated as the main Instill Core repo
- `make all/latest` now by default will launch all projects without building all components images from scratch
- `make all/latest PROJECT={core,vdp,model}` will launch the specified projects
- `make all/latest BUILD=true` will launch all projects and build all components from scratch
- `make down` will tear down everything in Instill Core
- `make all/latest {BUILD=true}` in the `vdp` and `model` repo will launch their dependent `core`
- `make down` in the `vdp` and `model` repo will tear down everything in Instill Core
This commit
- implement the above-mentioned logics
=> ci(Makefile): enhance Instill Core launch

.github/workflows/helm-integration-test-backend.yml, Makefile
Because
- we need to set `excludelocalconnector` to `false` in testing
This commit
- set `excludelocalconnector` to `false` in helm integration-test
=> ci(makefile): fix wrong config for helm test

README.md, examples/instill/streamlit-instance-segmentation-sync-http-http-stomata/README.md, examples/instill/streamlit-instance-segmentation-sync-http-http-stomata/main.py, examples/instill/streamlit-instance-segmentation-sync-http-http-stomata/utils.py, test/pipeline/helper.js, test/pipeline/verify-classification.js
Because
- there were so many typing errors and grammar errors in various files, so I tried and fix them
This commit
- fixes almost all the typo and grammar errors in the repo
=> chore(docs,tests): fix typo and grammar error

.github/workflows/helm-integration-test-backend.yml, .github/workflows/helm-integration-test-release.yml, .github/workflows/integration-test-backend.yml, .github/workflows/integration-test-release.yml, .github/workflows/make-all.yml
Because
- We have to create logic to cancel previous workflow if new one it triggered
- We have to set time limit for each workflow run
This commit
- set time limit to workflow run
=> ci(workflow): set time limit to workflow run

Makefile
Because
- when `instill/vdp-compore:release` image is not present in the local Docker Engine (i.e., launch from scratch), the launch of `core` will fail when `make all` (without `BUILD=true`)
This commit
- fix the logic by specifically using release version for the tag of `insitll/vdp-compose` and detecting whether the image is present or not to build.
=> ci(Makefile): fix dind image missing bug

README.md
Because
- We want to improve SEO.
This commit
- Use "No-Code/Low-Code" instead of "No-/Low-Code" to improve SEO on "no-code" and increase readability.
=> chore(docs): Update README.md for "No-Code"

README.md
Because
Doc link was wrong
This commit:
- fix doc link
=> chore(docs): replace bad docs link in README.md

charts/vdp/templates/_helpers.tpl, charts/vdp/templates/pipeline-backend/configmap.yaml
Because
- the pipeline-backend will connect to OpenFGA 
This commit
- update OpenFGA config
=> chore(helm): update OpenFGA config

.github/workflows/helm-integration-test-backend.yml, .github/workflows/integration-test-backend.yml
Because
- The tests running on MacOS are not robust in current CI environment, we decided to disable it temporally and will come back to this problem soon. 
This commit
- disable integration test on MacOS
=> chore(ci): disable integration test on MacOS

charts/vdp/templates/pipeline-backend/deployment.yaml, charts/vdp/templates/pipeline-backend/hpa.yml, charts/vdp/values.yaml
Because
- we need to update the HPA to scale the pod according to the requirement of pipeline backend containers
This commit
- update the HPA for pipeline backend containers
=> chore(helm): update the HPA for pipeline backend containers

charts/vdp/templates/controller-vdp/deployment.yaml, charts/vdp/templates/pipeline-backend/deployment.yaml, charts/vdp/values.yaml
Because
- we need to add the maxSurge and maxUnavailable values into the deployment
This commit
- add rolling update strategy
=> chore(helm): add rolling update strategy

README.md
Because
- I couldn't find the login credentials for onboarding in README.md file
This commit
- mentions the onboarding details in the README.md
=> docs(readme): include onboarding details in README.md

README.md
Because
- given the spread projects here and there, we need to make the `README.md` of each base project as concise and consistent as possible.
- Instill Core and Instill VDP have entered Open Beta
This commit
- make `README.md` content consistent
- remove Free Open Alpha free trial wording
- reword `unstructured data infrastructure` to `unstructured data ETL` as the infrastructure term can be too general
=> docs(readme): unify across all projects

.github/workflows/releases.yml
Because
- we need to update the helm chart version to beta
This commit
- update helm chart version to beta
=> ci(workflow): update helm chart version to beta

.github/workflows/make-latest.yml
Because
- We have to disable console building in make-latest.yml file due to consuming lot of time.
This commit
- Disable console building in make-latest.yml
=> chore(vdp): disable console building in make-latest.yml

.env, .github/CODEOWNERS, .github/CONTRIBUTING.md, .pre-commit-config.yaml, README.md
Because
- we now use the `exclude-` prefix to indicate a local development target
This commit
- update documentation
- update `README.md`
- upgrade pre-commit hooks
=> docs(CONTRIBUTING): update new profile logic

.github/CONTRIBUTING.md, .github/workflows/make-latest.yml, Makefile, docker-compose.build.yml, docker-compose.yml
Because
- the `profile` in Docker Compose is used to launch or build components when `make latest` and `make build-latest`
This commit
- fix the logic
=> ci(core): fix make build-latest PROFILE

docker-compose.yml
Because
- The pipeline_backend_worker has wrong `depends_on`
This commit
- change `temporal_admin_tools_pipeline` to `temporal_admin_tools_vdp`
=> chore(docker-compose): fix typo of `temporal_admin_tools_vdp`

charts/core/templates/NOTES.txt, charts/core/values.yaml
Because
- the Helm chart needs to catch up the latest backend verison
This commit
- update the db version in `pipeline-backend`
- update `NOTES.txt` to better instruct the next steps after helm installation
=> chore(helm): update chart

.github/workflows/helm-integration-test-backend.yml, .github/workflows/helm-integration-test-console.yml, .github/workflows/integration-test-backend.yml, .github/workflows/integration-test-console.yml, .github/workflows/make-all.yml, .github/workflows/make-latest.yml
Because
- when `workflow_call` from other repositories, the `actions/checkout` action by default checking out the caller repo, which is not what we want.
This commit
- specify the checked out repo to be always `instill-ai/instill-core`
=> ci(workflows): specify repo checkout

charts/core/templates/api-gateway/deployment.yaml
Because
- The api-gateway should start after the pipeline and model backend have started.
This commit
- Adds pipeline and model backend as dependencies of the api-gateway.
=> chore(helm): add pipeline and model backend as dependencies of api-gateway

charts/core/templates/registry/configmap.yaml, charts/core/templates/registry/cronjob.yaml, charts/core/templates/registry/deployment.yaml, charts/core/templates/registry/hpa.yaml, charts/core/templates/registry/service.yaml, charts/core/values.yaml
Because
- Under some circumstances, `registry` may not need to be deployed
This commit
- add `enabled` flag for registry service
=> chore(helm): add enabled flag for registry service

charts/core/Chart.yaml, charts/core/templates/controller-model/configmap.yaml, charts/core/templates/controller-model/deployment.yaml, charts/core/templates/controller-model/hpa.yml, charts/core/templates/controller-model/service.yaml, charts/core/templates/model-backend/configmap.yaml, charts/core/templates/model-backend/deployment.yaml, charts/core/templates/model-backend/hpa.yml, charts/core/templates/model-backend/post-install-job.yaml, charts/core/templates/model-backend/service.yaml, charts/core/templates/ray-service/monitor.yaml, charts/core/templates/ray-service/ray-service.yaml, charts/core/values.yaml
Because
- Allow deploying `Instill Core` without `Model` related services
This commit
- add flag to disable model related services
=> chore(helm): add flag to disable model related services

charts/core/templates/pvc.yaml, charts/core/templates/registry/configmap.yaml, charts/core/templates/registry/deployment.yaml, charts/core/values.yaml
Because
- `Model` service PVC not disabled by the `model` tag
- Support GCS storage backend for `registry` service
This commit
- fix `model` tag not disabling model pvc
- add support for GCS storage backend for `registry`
=> chore(helm): fix model tag pvc scope and support gcs registry storage

charts/core/templates/mgmt-backend/configmap.yaml, charts/core/templates/model-backend/configmap.yaml, charts/core/templates/pipeline-backend/configmap.yaml, charts/core/values.yaml
Because
- We are going to support a read-replica database to improve query throughput.
This commit
- Adds configuration for the read-replica database.
=> feat(helm): add configuration for read-replica database

charts/core/templates/mgmt-backend/configmap.yaml, charts/core/templates/model-backend/configmap.yaml, charts/core/templates/openfga/deployment.yaml, charts/core/templates/openfga/service.yaml, charts/core/templates/pipeline-backend/configmap.yaml
Because
- In the multi-region deployment, we will separate the read/write operations into different databases and OpenFGA engines.
This commit
- Adds connection settings for OpenFGA read replica.
=> chore(helm): add configuration for OpenFGA read replica

model-hub/model_hub_gpu.json
Because
- in model-backend 0.12.0, we are going to utilize 4 A100 40G GPU 
This commit
- update model config based on the following strategy
GPU1:
yolov7
mobilenetv2
yolov7-stomata
llava 13b (needs 26G VRAM)
GPU 2:
stable-diffusion-xl  (needs 16G VRAM)
controlnet-canny  (needs 16G VRAM)
GPU 3:
llama2-7b  (needs 16G VRAM)
llama2-7b-chat  (needs 16G VRAM)
GPU 4:
llamacode 7b   (needs 16G VRAM)
zephyr-7b    (needs 16G VRAM)
=> feat(model): support new models

model-hub/model_hub_gpu.json
Because
- in model-backend 0.23.0, we are going to utilize 4 A100 40G GPU 
This commit
- update model config based on the following strategy
GPU1:
yolov7
mobilenetv2
yolov7-stomata
llava 13b (needs 26G VRAM)
GPU 2:
stable-diffusion-xl  (needs 16G VRAM)
controlnet-canny  (needs 16G VRAM)
GPU 3:
llama2-7b  (needs 16G VRAM)
llama2-7b-chat  (needs 16G VRAM)
GPU 4:
llamacode 7b   (needs 16G VRAM)
zephyr-7b    (needs 16G VRAM)
=> chore(model): update llama2 model to gpu

charts/core/templates/pipeline-backend/configmap.yaml, charts/core/values.yaml
Because
- In the multi-region architecture, the Instill Model connector needs to connect to the model-backend through an external network instead of an internal network, we need to have a configuration for this.
This commit:
- Adds configuration to override the model-backend host.
=> chore(helm): add configuration to override model-backend host

.github/workflows/helm-integration-test-console.yml, .github/workflows/integration-test-console.yml
Because
- Console will upload test-results as artifact when the tests failed, but the workflow has some issue around, this PR fixes the issue
This commit
- fix console tests artifact upload issue
=> fix(cicd): fix uploading console tests artifact issue

model-hub/model_hub_gpu.json
Because
- We are going to host models on 2 A100 40G GPUs
This commit
- remove llamacode and controlnet-canny
- keep llama2-7b on GPU
- update wrong llava tag
=> chore(model_hub): fit models into 2 GPUs with llama2 on GPU

.github/workflows/helm-integration-test-backend.yml, .github/workflows/helm-integration-test-console.yml, .github/workflows/integration-test-backend.yml, .github/workflows/integration-test-console.yml
Because
- We have to remove the cancellation of the previous workflow step because cross signs could make users feel low-quality of our codebase
This commit
- remove the cancellation of the previous workflow
=> ci(workflow): remove the cancellation of previous workflow

charts/core/templates/pipeline-backend/configmap.yaml, charts/core/values.yaml
Because
- In Instill Cloud, the Instill Model connector will frequently send GET requests to /models endpoint, as it connects to Instill Model through an external network, resulting in poor performance. Since we have a static model list in Instill Cloud for now, we can implement a temporary workaround by caching the model list to improve performance.
This commit
- Adds setting for a workaround to improve Instill Cloud performance
=> chore(helm): add setting for a workaround to improve Instill Cloud performance

charts/core/templates/registry/deployment.yaml, charts/core/values.yaml
Because
- We are missing `extraVolumeMounts` in registry deployment.yaml
- We have wrong redis host in registry deployment.yaml
This commit
- fix redis host and add extra volume mounts for registry service
=> chore(helm): fix redis host and add extra volume mounts

model-hub/model_hub_gpu.json
Because
- we are moving llama2-7b to CPU and add controlnet
This commit
- adjust model list
=> chore(model_hub): adjust model list

charts/core/templates/ray-service/ray-service.yaml, charts/core/values.yaml
Because
- In current setup, GPU node has CPU resources available, causing pure CPU model will sometime be scheduled onto GPU node, which is not desirable, we want CPU models to only be scheduled on CPU node.
This commit
- mark GPU node as no CPU resource available for scheduling
=> chore(helm): mark GPU node as no CPU resource available

charts/core/templates/artifact-backend/deployment.yaml, charts/core/templates/artifact-backend/service.yaml, charts/core/values.yaml
Because
- Mid-sprint release shouldn't include artifact-backend
This commit
- Adds flag to artifact-backend Helm chart to disable deployment
=> chore(artifact): disable artifact-backend in release

.github/workflows/helm-integration-test-backend.yml
Because
- We should build the latest image when testing.
This commit
- Fixes helm test workflow.
=> chore(github): fix helm test workflow

Makefile, docker-compose-latest.yml
Because
- local integration-test-latest won't pass
This commit
- fix model-backend tag after `build-latest`
- make ray server image tag fixed temporary
=> chore(makefile): fix latest integration-test

model-hub/model_hub_gpu.json
Because
- we are going to host more models
This commit
- add llamacode-7b
- make zephyr runs on gpu
=> chore(model_hub): add llamacode and make zephyr runs on gpu

docker-compose.yml
Because
- Ray server is having unusual cpu usage during idle, which is caused by mistakenly set health-check interval
This commit
- update ray server health-check interval
=> chore(compose): fix ray server health-check interval causing cpu spike

charts/core/templates/mgmt-backend/deployment.yaml
Because
- The `mgmt-backend-migration` container needs to run a Temporal workflow
This commit
- Mounts Temporal TLS volume for `mgmt-backend-migration`.
=> chore(helm): mount temporal tls volume for mgmt-backend-migration

README.md, docker-compose-build.yml, docker-compose-latest.yml, docker-compose-nvidia.yml, docker-compose-observe.yml, docker-compose.yml
Because
- `version` has been deprecated in the Docker Compose `v2`
This commit
- remove `version` in the compose file and update `README.md`
=> chore(docker-compose): remove version

.github/workflows/sync-version-with-website.yml
Because
- We want to sync the version to instill.tech website automatically.
This commit
- Adds Github Action workflow for this.
=> ci(github): sync version to instill.tech website

charts/core/values.yaml, model-hub/model_hub_gpu.json
Because
- Using nightly build of 3rd party dependency might encounter unwanted instability
This commit
- use stable version of kuberay
- update `stable-diffusion-xl` hardware type to avoid OOM
=> chore(helm): use fixed version of kuberay

.gitignore, docker-compose.yml
Because
wrong health check, docker compose fails in healthcheck of artifact backend
This commit
using `cur`l to send `GET` method instead of `HEAD` method from `wget`
=> fix(artifact): modify healthy check request

.all-contributorsrc, .github/CONTRIBUTING.md, .github/triage.md, .github/workflows/add-comment-to-issue.yml, README.md
Because
- we are going to archive the [community](https://github.com/instill-ai/community) and move the content to the `instill-core` repo
This commit
- integrate the `community` repo content with the `instill-core` repo
=> chore(community): migrate community content

.all-contributorsrc, .github/CONTRIBUTING.md, README.md
Because
- `README.md` is out-dated
This commit
- update `README.md` to catch up the latest Instill Core stack
=> docs(readme): update README.md

charts/core/values.yaml
Because
db migration is outdated
This commit
use correct version
=> chore(artifact): use correct db version

charts/core/templates/mgmt-backend/deployment.yaml, charts/core/values.yaml
Because
- Cloud features require migrations to be run on a given cluster.
This commit
- Creates the `isPrimaryCluster` variable and uses it to enable the migration process on `mgmt-backend`.
=> feat(mgmt): run migration only on main cluster in mgmt-backend

charts/core/templates/_helpers.tpl, charts/core/templates/model-backend/configmap.yaml, charts/core/templates/model-backend/deployment.yaml, charts/core/templates/pvc.yaml, charts/core/values.yaml, docker-compose.yml
Because
- deployment config should be preserved even if model-backend pod restart for unknown reasons
This commit
- store deployment config in pvc
=> chore(model): add pvc for deployment config

model-hub/model_hub_gpu.json
Because
- Stable Diffusion XL can run on `L4` GPU
This commit
- update sdxl model hardware type
=> chore(model-hub): update sdxl model hardware type

model-hub/model_hub_gpu.json
Because
- CodeLlama task type is wrong
This commit
- fix CodeLlama task type
=> chore(model-hub): fix llamacode task type

charts/core/Chart.yaml, charts/core/values.yaml
Because
- we need one central toggle
This commit
- add artifact's toggle on its dependency, milvus.
=> chore(milvus): add toggele on milvus

.github/workflows/add-comment-to-issue.yml, LICENSE, charts/core/LICENSE
Because
- Instill Core main codebase is now with Instill Community License
This commit
- update license files and wording
=> docs(license): update project license

charts/core/templates/mgmt-backend/configmap.yaml, charts/core/templates/pipeline-backend/configmap.yaml
Because
- Flush interval config param was changed to duration in [`pipeline-backend`](https://github.com/instill-ai/pipeline-backend/pull/508/files#diff-38df760413887d0cc4ee5707919e6390456a863d326f6080644cc3d9c72e4bbaR37) and [`mgmt-backend`](https://github.com/instill-ai/mgmt-backend/commit/3d529fac4e407c1de2a94ce83d7b8e947733c24c#diff-38df760413887d0cc4ee5707919e6390456a863d326f6080644cc3d9c72e4bbaR43).
This commit
- Updates Helm charts accordingly.
=> chore(mgmt): update mgmt and pipeline config

charts/core/templates/_helpers.tpl, charts/core/templates/artifact-backend/configmap.yaml, charts/core/values.yaml
Because
artifact backend needs the connection info of minio
This commit
adds minio-related connection setting
=> chore(artifact): add minio and mgmt in configmap

charts/core/values.yaml
Because
- https://github.com/instill-ai/pipeline-backend/pull/529 introduced a new
migration.
This commit
- Bumps the pipeline DB version
=> chore(pipeline): bump pipeline migration version

charts/core/values.yaml
Because
- model-backend has a new migration version
This commit
- bump model db version
=> chore(model): bump model db version

charts/core/templates/pipeline-backend/configmap.yaml
Because
- In pipeline-backend, we connect to Instill Cloud to download the preset pipelines.
This commit
- Adds the Instill Cloud host setting for pipeline-backend.
=> chore(helm): add instillcloud host setting for pipeline-backend

charts/core/templates/ray-service/ray-service.yaml
Because
- Current ray worker will respawn indefinitely after non zero exit code
This commit
- add retry limit for ray worker process
=> chore(helm): add retry limit for ray worker process

.gitignore, charts/core/templates/artifact-backend/configmap.yaml, charts/core/values.yaml
Because
1. artifcat backend needs the necessary config to connect pipeline backend
2. artifact backend uses the number of works in config
3. artifact backend need the necessary config to connect milvus
This commit
add necessary configs in configmap.yaml
=> chore(KB): add needed configs for file-to-embedding process

charts/core/templates/model-backend/configmap.yaml
Because
- Influxdb config is required for model-backend to send metrics
This commit
- add influxdb config in model-backend configmap
=> chore(helm): add influxdb config in model-backend configmap

docker-compose.yml
Because
seems in image build environment using strict(or old) yaml parser for docker compose.
This commit
use string instead of bool
=> fix(core): make value in yaml compatible with strict parser

charts/core/values.yaml
Because
we don't want milvus and its deps consume resource of other service.
This commit
add node selector for its deps
=> chore(milvus): add node selector to its deps

charts/core/values.yaml
Because
- https://github.com/instill-ai/pipeline-backend/pull/548 migrates recipes to
use kebab-case in JQ task input fields.
This commit
- Updates the references to the latest migration.
=> chore(pipeline): use kebab-case in JSON operator

.github/workflows/releases.yml
Because
the artifact backend image used in helm install is out of date.
This commit
upgrade the version for helm ce user
=> chore(artifact): add version update in helm release

charts/core/values.yaml
Because
- observability stack can be resource intensive
This commit
- set `observability` flag to false by default
=> chore(helm): disable observability by default

README.md
Because
- We want to add support `instill-core` on Windows.
This commit
- Provides documentation for installing `instill-core` on Windows through WSL2
=> chore(main): add documentation for Windows (WSL2) installation

.env, docker-compose-latest.yml
Because
sometime we need to connect to openfga directly
This commit
expose its port on machine
=> chore(openfga): set port on machine

charts/core/templates/registry/configmap.yaml, charts/core/values.yaml
Because
- We would like to support `s3` as registry storage backend
This commit
- add `s3` in registry config
=> feat(registry): support s3 as storage backend

charts/core/templates/artifact-backend/configmap.yaml, charts/core/values.yaml
Because
artifact needs the openfga related config and migrate the db
This commit
add config of openfga and update the db migration version
=> feat(artifact): update cm for openfga

charts/core/templates/model-backend/configmap.yaml, charts/core/values.yaml
Because
- `model-backend` has been updated to `8`
This commit
- bump model db version
=> chore(helm): bump model db version

charts/core/templates/pipeline-backend/deployment.yaml
Because
- The pipeline pod security settings are incorrect.
This commit
- Fixes the pipeline pod permissions.
=> fix(helm): fix pipeline pod permission

charts/core/values.yaml
Because
we might need to scale minIO up in the future.
This commit
make minIO in distributed mode
=> feat(minIO): change distributed mode

charts/core/README.md
Because
- the Helm chart `README.md` is out-dated
This commit
- update the `README.md`
=> chore(helm): update README.md

charts/core/templates/pipeline-backend/deployment.yaml
Because
- We want to pass env variables to the migration command to perform extra migrations in cloud-only environments.
This commit
- Reads the environment values defined in the Helm charts
=> chore(pipeline): apply environment variables on migration command

Makefile
Because
- `make all` and `make latest` should not build the docker-in-docker image by default
This commit
- fix the Makefile targets
=> ci(Makefile): fix make all/latest

charts/core/values.yaml
Because
log amount is too much
This commit
change the log level to error
NOTE: we may chang back when it is necessary.
=> chore(milvus): adjust milvus's log level

charts/core/values.yaml
Because
- we need to update db version to update recipe for web component refactor
This commit
- update db version
=> chore(vdp): udpate db version for web component update

charts/core/templates/pipeline-backend/configmap.yaml, charts/core/values.yaml
Because
- We need to configure connection settings for the Artifact component.
This commit
- Sets up the infrastructure for the Artifact component.
=> chore(helm): sets up Artifact component infra

charts/core/templates/ray-service/ray-service.yaml, docker-compose.yml
Because
- RayCluster autoscaler is emitting lengthy unnecessary logs
This commit
- disable periodic autoscaler status logging
=> chore(ray): disable periodic autoscaler status logging

model-hub/model_hub_gpu.json
Because
- Due to availability problem of `A100` on GCP, we are going to switch hardware type of `llava` model to `L4` GPU
- update llava version to support weights offloading
This commit
- update llava model version and hardware type
=> chore(model_hub): update llava model version

.gitignore, charts/core/templates/model-backend/configmap.yaml, charts/core/values.yaml
related to https://github.com/instill-ai/model-backend/pull/651
Because
- model backend needs to store data in mino
This commit
- added config for minio in model-backend
=> chore(model): sets up minio for model-backend

charts/core/templates/pipeline-backend/configmap.yaml, charts/core/values.yaml
Because
- The minio setting is missing.
This commit
- Adds minio setting for pipeline-backend.
=> chore(helm): add minio setting for pipeline-backend

charts/core/templates/pipeline-backend/configmap.yaml, charts/core/values.yaml
Because
- The host/port override for the model and artifact backends is no longer needed.
This commit
- Removes the host/port override for the model and artifact backends.
=> chore(charts): remove host/port override for model and artifact backend

charts/core/values.yaml
Because
- Integration feature modifies the pipeline database.
This commit
- bump pipeline-backend db version
=> chore(helm): bump pipeline-backend db version

charts/core/templates/model-backend/configmap.yaml, charts/core/values.yaml
Because
- model-backend configs changed
This commit
- add task schema version hash in values.yaml
- bump model db version
=> chore(helm): add task schema version and bump model db version

schema/ai-tasks.json
Because
- content type title are all the same
This commit
- update content type title
=> chore(schema): update content type title

.github/workflows/helm-integration-test-backend.yml, .github/workflows/helm-integration-test-console.yml, .github/workflows/helm-integration-test-latest.yml, .github/workflows/helm-integration-test-release.yml, .github/workflows/integration-test-backend.yml, .github/workflows/integration-test-console.yml, .github/workflows/integration-test-latest.yml, .github/workflows/integration-test-release.yml, .github/workflows/make-all.yml, .github/workflows/make-latest.yml, .github/workflows/releases-helm-charts.yml, .github/workflows/releases.yml, Makefile
Because
- we can safely run the integration tests on only Linux because instill-core relies on Docker Desktop on MacOS.
- as the codebase continues to evolve the `timeout 60` for the integration tests is no longer enough
This commit
- remove integration tests for MacOS
- increase timeout to 120
- upgrade to actions/checkout@v4 to address the warning:
- disable image build in integration-test
```
The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
```
=> ci(workflows): refactor integration tests

schema/ai-tasks.json
Because
- Embedding task input is unnecessary complex
This commit
- update embedding task schema
=> chore(schema): update embedding task schema

schema/ai-tasks.json
Because
- text-to-image output schema has wrong instillformat
This commit
- fix text-to-image output instillformat
resolves INS-6230
=> chore(schema): fix text-to-image output instillformat

charts/core/values.yaml
Because
- The model & pipeline db version need to be updated.
This commit
- Updates model db version to 11 and pipeline to 27.
=> chore(helm): update model & pipeline db version

schema/ai-tasks.json, schema/schema.json
Because
- `title` property should be uppercase
This commit
- use uppercase for title
=> chore(schema): use uppercase for title

README.md
Because
- https://github.com/instill-ai/pipeline-backend/pull/678 moves `component` under `pipeline-backend`
This commit
- updates the `component` section in the README
=> chore(docs): include component in VDP section

charts/core/templates/api-gateway/configmap.yaml, charts/core/values.yaml
Because
- api-gateway will potentially need to connect to additional hosts
This commit
- add additional host to api-gateway configmap
=> chore(helm): add additional host to api-gateway configmap

model-hub/model_hub_gpu.json
Because
- Jina model has wrong hardware type
This commit
- fix hardware type
=> chore(model-hub): fix hardware type

.github/workflows/helm-integration-test-latest.yml, .github/workflows/integration-test-latest.yml
Because
- We have to add artifact-backend for the integration test
This commit
- add artifact-backend integration test
=> chore(github): add artifact-backend integration test

charts/core/values.yaml
Because
- https://github.com/instill-ai/pipeline-backend/pull/699 introduces a new
database version.
This commit
- Updates the database version.
=> chore(vdp): bump database version

charts/core/values.yaml
Because
- AI task schema version is outdated in model-backend configmap
This commit
- update model task schema version
=> chore(helm): update model task schema version

charts/core/Chart.yaml, charts/core/templates/_helpers.tpl, charts/core/templates/model-backend/configmap.yaml, charts/core/templates/ray-service/monitor.yaml, charts/core/templates/ray-service/ray-service.yaml, charts/core/values.yaml
Because
- allow user to install `RayCluster` in separate namespace
This commit
- support separate namespace installation for `RayCluster`
=> feat(helm): support isolated namespace for ray cluster

.github/workflows/sync-version-with-api-docs.yml
Because
- https://github.com/instill-ai/protobufs/pull/494 uses a single file to configure the OpenAPI definition info.
This commit
- Update workflow keeping the version in the OpenAPI docs in sync with `instill-core`.
=> chore(docs): use new conf file for OpenAPI version

.github/workflows/integration-test-backend.yml
Because
- Latest `pipeline-backend` tests OAuth connection creation using some environment variables ([ref](https://github.com/instill-ai/pipeline-backend/blob/main/.github/workflows/integration-test.yml#L80))
This commit
- Adds such variables to the build on the CI.
=> fix(component): add dummy OAuth information for pipeline-backend tests

charts/core/templates/_helpers.tpl
Because
there is a lack on helpers.tpl
This commit
adds a new Helm template helper `core.minio.port` to define MinIO's default port (9000)
=> fix(api-gateway): add minio port in _helpers.tpl

.github/workflows/helm-integration-test-backend.yml, .github/workflows/integration-test-backend.yml, .github/workflows/make-all.yml, .github/workflows/make-latest.yml, Dockerfile
Because
- xk6-sql released a new version with breaking changes.
This commit
- Pins xk6-sql to a specific version to maintain compatibility.
=> chore(ci): pin xk6-sql to a specific version to maintain compatibility

.github/workflows/helm-integration-test-backend.yml, charts/core/README.md
Because
- https://github.com/instill-ai/pipeline-backend/pull/799 commented out some checks in `pipeline-backend`'s integration tests because they depended on some environment variables that the Helm charts weren't passing.
This commit
- Pass the required OAuth client variables so the full `pipeline-backend` suite can be run.
=> fix(helm): pass OAuth configuration variables on integration tests

charts/core/templates/pipeline-backend/configmap.yaml
Because
- we need the env var
This commit
- add config
=> chore(pipeline-backend): add artifact config for pipeline-backend

charts/core/templates/artifact-backend/configmap.yaml, charts/core/values.yaml
Because
blob service in artifact need the config to know the its domain
This commit
add the blob domain in config for different environment
=> feat(blob/artifact): add blob domain in config

README.md
Because
- hacktoberfest 2024 had new contributors
This commit
- add hacktoberfest 2024 contributors
=> chore(readme): add hacktoberfest 2024 contributors

charts/core/values.yaml
Because
- `pipeline-backend` added a new DB version in https://github.com/instill-ai/pipeline-backend/pull/938.
This commit
- Updates the version in the helm charts.
=> chore(helm): update pipeline database version

docker-compose-build.yml
Because
- The pipeline-backend image could not be built due to a Golang version mismatch.
This commit
- Resolves the image build issue for pipeline-backend.
Note:
We plan to remove the library version override in the future. Each microservice will fully control its versioning, eliminating reliance on the .env file in this repository.
=> chore(docker): fix image build problem for pipeline-backend

.github/workflows/helm-integration-test-backend.yml, .github/workflows/helm-integration-test-console.yml, .github/workflows/integration-test-backend.yml, .github/workflows/integration-test-console.yml, .github/workflows/make-all.yml, .github/workflows/make-latest.yml
Because
- mono service no longer exist in github runner instance
This commit
- remove step to stop mono service
=> fix(ci): remove step to stop mono service

.github/workflows/releases-helm-charts.yml
Because
- The workflow was not able to fetch the gh-pages origin
This commit
- fix release helm chart github action workflow
=> fix(workflow): fix release helm chart github action workflow

.env.component-test, .github/workflows/integration-test-backend.yml, Makefile, docker-compose.yml
Because
- Integration tests passed on the CI because dummy values were injected for
the OAuth configuration. This was required to enable OAuth for the GitHub
component, whose OAuth integration was later tested. On local testing,
however, we relied on these values to be present on .env.component
This commit
- Creates an .env.component-test file, which contains the dummy values.
This is used on `make *test*` in order not to overwrite local
configuration values.
=> fix(test): inject dummy OAuth values in integration tests

charts/core/templates/artifact-backend/deployment.yaml, charts/core/values.yaml, docker-compose.yml
Because
- We are refactoring the preset pipeline mechanism. The preset pipelines will now be created programmatically by other services instead of being downloaded via the preset pipeline downloader. For example, the preset pipelines used by artifact-backend will be created by artifact-backend itself.
This commit
- adds artifact-backend-init cmd for creating preset pipelines.
=> chore(helm,docker): add artifact-backend-init cmd

charts/core/templates/artifact-backend/configmap.yaml, charts/core/templates/model-backend/configmap.yaml, charts/core/templates/pipeline-backend/configmap.yaml, charts/core/values.yaml
Because
- MinIO config params lead to the conclusion that the root credentials are needed, when any valid user/pass with the right permissions (bucket & object) will be valid.
This commit
- Updates the configuration for the MinIO client.
- Helm charts are modified to match the config changes in:
- https://github.com/instill-ai/pipeline-backend/pull/977
- https://github.com/instill-ai/model-backend/pull/729
- https://github.com/instill-ai/artifact-backend/pull/145
=> chore(minio): do not configure MinIO with root credentials

charts/core/values.yaml
Because
- artifact-backend has new db version
This commit
- bump artifact db version
=> chore(helm): bump artifact db version

charts/core/templates/artifact-backend/configmap.yaml, charts/core/values.yaml
Because
- MinIO audit log webhook needs to be enabled.
This commit
- Add MinIO audit log webhook flag to Helm chart.
=> chore(artifact): log MinIO audit logs

charts/core/templates/artifact-backend/configmap.yaml
Because
- artifact-backend now connects to model-backend
This commit
- update artifact config
=> chore(helm): update artifact config

charts/core/templates/artifact-backend/configmap.yaml, charts/core/values.yaml
Because
- The `logminioaudit` configuration value has been removed from `artifact-backend`.
This commit
- Reverts commit f2c2660d89a81e2208ceb70462039b6d67a8202d.
=> chore(artifact): remove MinIO log toggle

.env, .github/workflows/integration-test-backend.yml, .github/workflows/integration-test-console.yml, .github/workflows/make-all.yml, .github/workflows/make-latest.yml, Makefile
Because
- the Makefile targets are for local development and testing purpose, the the service images have been also built from scratch to ensure integrity. In this case, `BUILD` and `BUILD_CORE_DEV_IMAGE` are redundant as they have been set always `true` anyway.
This commit
- remove `BUILD` and `BUILD_CORE_DEV_IMAGE` env variables
- remove `make build-release` in `make all` and `make build-latest` in `make latest`, i.e., `make all` and `make latest` will use only remote pre-built images and won't build service images locally
- fix typos
=> ci(Makefile): remove build-related env variables

charts/core/Chart.yaml, charts/core/README.md, charts/core/README.md.gotmpl
Because
- we are replacing `helm.instill.tech` with `helm.instill-ai.dev` to cohere the new domain layout
This commit
- update charts' README docs accordingly
=> chore(charts): update README for new domain instill-ai.dev

charts/core/templates/_helpers.tpl, charts/core/templates/pipeline-backend/deployment.yaml, charts/core/values.yaml
Because
- We have to separate pipeline-backend and pipeline-backend-worker
This commit
- separate pipeline-backend and pipeline-backend-worker
=> chore(pipeline-backend): separate pipeline-backend and pipeline-backend-worker

charts/core/templates/pipeline-backend/configmap.yaml
Because
- instill-ai/pipeline-backend#989 fixes a bug in the worker initialisation.  This requires the `InstanceID` config value to be set.
This commit
- Adds the `instanceid` value to `pipeline-backend*`'s configmap.
=> fix(worker): use pipeline server host in pipeline client

charts/core/templates/_helpers.tpl, charts/core/templates/pipeline-backend/configmap.yaml, charts/core/templates/pipeline-backend/service.yaml, charts/core/values.yaml, configs/grafana/dashboards/all.yml, configs/grafana/temporal/temporal-go-java-sdks-tally.json, configs/prometheus/config.yaml, docker-compose-observe.yml
Because
- `pipeline-backend` introduced config changes in instill-ai/pipeline-backend/pull/990
This commit
- Updates the pipeline Helm charts
- Scrapes the Temporal metrics on docker-compose and exposes a Grafana dashboard, following [this guide
](https://docs.temporal.io/cloud/metrics/prometheus-grafana#grafana-dashboards-setup)
=> feat(pipeline): collect Temporal SDK metrics

docker-compose.yml
Because:
- The model-backend-worker failed to start.
This commit:
- Adds the missing Ray Serve address for model-backend-worker.
=> chore(docker): add missing Ray Serve address for model-backend-worker

.github/workflows/helm-integration-test-backend.yml
Because:
- A step was accidentally removed.
This commit:
- Fixes a missing variable in the Helm integration test.
=> ci(github): fix the missing variable in Helm integration test

charts/core/templates/artifact-backend/deployment.yaml, charts/core/templates/mgmt-backend/deployment.yaml, charts/core/templates/openfga/deployment.yaml
Because
- We have to add env in mgmt-backend and artifact-backend's migration container
This commit
- add env in mgmt-backend and artifact-backend's migration container
=> chore(migration): add env in mgmt-backend and artifact-backend's migration container

charts/core/Chart.lock, charts/core/Chart.yaml, charts/core/README.md, charts/core/templates/_helpers.tpl, charts/core/templates/model-backend/configmap.yaml, charts/core/templates/ray/configmap.yaml, charts/core/templates/ray/monitor.yaml, charts/core/templates/ray/raycluster.yaml, charts/core/values.yaml
Because
- KubeRay 1.3.2 includes important bug fixes and performance improvements over previous versions
- Configuration paths needed to be updated to match the new Ray container structure
- Previous podman configuration setup had inconsistent naming conventions
This commit
- Updates kuberay-operator from previous version to 1.3.2
- Changes container mount paths from `/etc/containers/` to `/home/ray/.config/containers/` for clearer precedence.
- Standardizes podman volume and configmap naming using consistent templates
- Removes deprecated service configuration in favor of new approach
=> chore(helm): upgrade kuberay-operator to version 1.3.2

charts/core/grafana-dashboards/api-gateway/for-prometheus.json, configs/grafana/dashboards/api-gateway/for-prometheus.json
Because
- the dashboard tag for KrakenD is outdated.
This commit
- updates tag for KrakenD
=> chore(dashboard): update tag for KrakenD

Makefile, docker-compose.yml
Because
- we are running rootful mode for Podman DinD for containerized application deployment with Ray Serve, `fuse-overayfs` driver is the correct one to use.
This commit
- remove the corresponding docker compose configuration
=> fix(ray): fix podman fs issue causing deployment hanging

.env, Makefile, charts/core/Chart.lock, docker-compose-build.yml, docker-compose-latest.yml
Because
- the dependency between Instill Core backends is getting complex, excluding a service might cause the entire suite spun up failure.
This commit
- reverse the logic to exhaustively specify services to spin up.
=> ci(compose): reverse COMPOSE_PROFILES logic

docker-compose.yml
Because
- when the host compute resource is packed, the spin-up time can take longer than usual
This commit
- increase the Docker Compose service healthcheck retries value
=> ci(composes): increase the healthcheck retries value

Makefile
Because
- The curl command to check the model status doesn’t work when using `make all`, since the port is not exposed.
This commit
- Runs a container to check the model status.
=> ci(makefile): use a container to check model status

Makefile
Because
- hardcoded service host and port is not good practice
This commit
- used environment variables for Ray host and port used in the Makefile.
=> ci(Makefile): use env variable for ray host and port

charts/core/values.yaml
This commit
- Bumps the database version to use migration in instill-ai/artifact-backend#197
=> chore(catalog): add converting pipelines to database model

.github/CONTRIBUTING.md
Because
- the `CONTRIBUTING.md` content is out-dated
This commit
- updated the document
=> docs(CONTRIBUTING): update guideline

Dockerfile, Makefile.helper, docker-compose-build.yml
Because
- the current build-time backend versioning logic is wrong.
This commit
- fixed the versioning logic and assigned short commit hash to all backend services.
=> ci(compose): adopt short commit hash for all service versions

docker-compose.yml
Because
- images especially `latest` tag ones should be always re-pulled to avoid stale context.
This commit
- add `pull_policy: always` in each compose service.
=> ci(compose): add pull_policy: always

docker-compose.yml
Because
- The original health check command `wget --spider` sends a `HEAD`` request to the backend, while the backend only supports `GET`.
This commit
- Fixes the health check command.
=> fix(compose): fix health check command

charts/core/templates/mgmt-backend/configmap.yaml, charts/core/templates/model-backend/configmap.yaml, charts/core/values.yaml
Because
- we updated the Temporal config format in model and mgmt-backend.
This commit
- updates the outdated Temporal config in Helm Chart
=> chore(helm): update outdated Temporal config

.env, Makefile.helper, docker-compose.yml
Because
- model integration test was broken due to wrong init configuration. It's now fixed and I'd like to improve the overall config naming between model-backend and instill-core.
This commit
- update the initmodel config.
=> ci(model): fix model integration test

docker-compose.yml
Because
- we are going to largely refactor `instill-core` to become a deploy-only repository, images should be possibly prepared locally or remotely.
This commit
- set the service image pull_policy to `missing`.
=> ci(compose): set image pull_policy: missing

docker-compose.yml
Because
- when the local host compute resource is low-availability, the launch time will take longer than it normally does.
This commit
- increases service healthcheck overall timeout (by increasing retries).
=> ci(compose): increase service healthcheck timeout

.github/workflows/update-service-version.yml
Because
- we want to use the Git commit hash as the service version to enable automated version synchronization.
This commit
- provides a workflow to sync the service version automatically.
=> ci(github): add workflow for syncing service version

Dockerfile, Makefile.helper
Because
- make short commit SHA naming consistent across all places.
This commit
- replaces `COMMIT_SHORT_HASH` with `COMMIT_SHORT_SHA`
=> ci(compose): rename env variables

docker-compose.yml
Because
- the mgmt-worker should start after mgmt-backend.
This commit
- swaps the service order.
=> ci(compose): fix mgmt-backend service order

.github/CONTRIBUTING.md, .github/workflows/integration-test.yml, .github/workflows/make.yml, Dockerfile, Makefile, Makefile.helper, README.md, docker-compose-dev.yml
Because
- we want to make the `instill-core` service dependencies clearer and more traceable. To achieve this, we will retire the use of the `latest` image tag for each service. All services must now provide a Git tag or commit hash as the version.
- with the retirement of the `latest` tag, there's no longer a need to maintain separate release/latest scripts, so we will merge them.
This commit
- simplifies deployment by using the Git commit hash as the service version.
- renames `docker-compose-latest.yml` to `docker-compose-dev.yml` to better reflect its purpose for development.
- merges all release/latest scripts into unified ones. For example:
- `make latest`, `make all` → `make compose-run`
- `make compose-integration-test-latest`, `make compose-integration-test-release` → `make …
=> ci(makefile): simplify deployment by using git hash for service version

.github/workflows/update-service-version.yml, Makefile
Because
- we need to control the length of commit sha
This commit
- uses a fixed length of commit sha
=> ci(github): use a fixed length of commit sha

docker-compose.yml
Because
- `model-backend` takes more than 15 secs to launch.
This commit
- increases `the start_period`.
- revert dependency order.
=> ci(compose): increase model-backend healthcheck start_period

.github/workflows/update-service-version.yml, Makefile.helper, charts/core/values.yaml
Because
- we want to automatically update the image tags in Helm chart.
This commit
- updates the service image tag in Helm chart automatically.
- makes the image tag sync with the versions in .env file
=> ci(github): update the service image tag in Helm chart automatically

release-please/config.json
Because
- `release-please` can't really handle nested packages in a monorepo, the Helm chart will release with its own CI workflow.
This commit
- removes chart release-please configuration.
=> ci(release-please): remove helm pacakge config

.github/workflows/update-service-version.yml
This commit
- supports git tag as version when syncing service version
=> ci(github): support git tag as version when syncing service version

charts/core/templates/api-gateway/deployment.yaml
This commit
- removes temporal-admin-tools from api-gateway deployment
=> fix(helm): remove temporal-admin-tools from api-gateway deployment

charts/core/templates/mgmt-backend/configmap.yaml, charts/core/templates/model-backend/configmap.yaml, charts/core/templates/pipeline-backend/configmap.yaml, charts/core/values.yaml
Because
- we want to use API key authentication for Temporal to simplify deployment.
This commit
- uses API key authentication for Temporal
=> chore(helm): use api-key for Temporal auth

docker-compose.yml
This commit
- adopts the common binary `curl` for health check among services.
=> ci(compose): replace wget with curl for all service health checks

charts/core/templates/registry/maintenance.yaml
Because
- We have to use bitnamisecure/kubectl rather than bitnami/kubectl docker image
This commit
- replace the docker image for kubectl use
=> chore(registry): replace the docker image for kubectl use
